// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var count = {
  contents: 0
};

function renderCountTextView(n) {
  var el = document.getElementById("count");
  el.innerText = "Count is " + String(n);
  
}

function updateCount(steps) {
  count.contents = count.contents + steps | 0;
  
}

function renderView(steps) {
  updateCount(steps);
  renderCountTextView(count.contents);
  
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  count ,
  renderCountTextView ,
  updateCount ,
  renderView ,
  plusOne ,
  minusOne ,
  
}
/* plusButton Not a pure module */
