// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var mainEl = document.querySelector("main");

var count = {
  contents: 0
};

function renderCountTextView(n) {
  var el = document.getElementById("count");
  el.innerText = "Count is " + String(n);
  
}

function updateCount(steps) {
  count.contents = count.contents + steps | 0;
  
}

function renderView(steps) {
  updateCount(steps);
  renderCountTextView(count.contents);
  
}

function modifyCountClass(param) {
  var tag = document.getElementById("count");
  if (count.contents > 0) {
    tag.className = "count count-positive";
  } else if (count.contents < 0) {
    tag.className = "count count-negative";
  } else {
    tag.className = "count count-zero";
  }
  
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

mainEl.addEventListener("click", modifyCountClass);

export {
  plusButton ,
  minusButton ,
  mainEl ,
  count ,
  renderCountTextView ,
  updateCount ,
  renderView ,
  modifyCountClass ,
  plusOne ,
  minusOne ,
  
}
/* plusButton Not a pure module */
